#!/usr/bin/env python3

import nef_app
import typer
nef_app.app = typer.Typer()


# import components which will self register, this could and will be automated
import transcoders.nmrview
import tools.header

if __name__ == "__main__":
    nef_app.app()
