from fastmcp import FastMCP
from fastmcp.server.transforms import ResourcesAsTools
from fastmcp.tools import Tool

from nef_pipelines.lib.util import get_version
from nef_pipelines.tools.ai.mcp_commands import (  # noqa: F401 — import triggers @mcp_tool decorations
    _MCP_TOOLS,
)
from nef_pipelines.tools.ai.mcp_lib import (
    _RESOURCES,
    _SKILLS,
    _build_full_orientation,
    _get_resource_description_from_filename,
    _get_resource_name_from_filename,
    _resource_sort_key,
)


class _NefResourcesAsTools(ResourcesAsTools):
    """\
    ResourcesAsTools subclass that prefixes generated tool names with 'nef_'
    for consistency with the rest of the NEF-Pipelines MCP tool namespace.

    list_resources  → nef_list_resources
    read_resource   → nef_read_resource
    """

    def _make_list_resources_tool(self) -> Tool:
        tool = super()._make_list_resources_tool()
        return tool.model_copy(update={"name": "nef_resources_list"})

    def _make_read_resource_tool(self) -> Tool:
        tool = super()._make_read_resource_tool()
        return tool.model_copy(update={"name": "nef_resources_read"})

    async def get_tool(self, name: str, call_next, *, version=None) -> Tool | None:
        if name == "nef_resources_list":
            return self._make_list_resources_tool()
        if name == "nef_resources_read":
            return self._make_read_resource_tool()
        return await call_next(name, version=version)


def _register_resources(mcp_server, directory, uri_prefix="nef://", sort_key=None):
    """Register markdown files from a directory as MCP resources.

    Args:
        mcp_server: FastMCP server instance
        directory: Path to directory containing .md files
        uri_prefix: URI prefix (e.g., "nef://" or "nef://skill/")
        sort_key: Sort key function (defaults to alphabetical by name)
    """
    if sort_key is None:

        def sort_key(f):
            return f.name

    for markdown_file in sorted(directory.iterdir(), key=sort_key):
        if not markdown_file.name.endswith(".md"):
            continue
        name = _get_resource_name_from_filename(markdown_file.name)
        description = _get_resource_description_from_filename(markdown_file.name)
        uri = f"{uri_prefix}{name}"

        def _make_reader(f):
            def _reader() -> str:
                return f.read_text()

            return _reader

        mcp_server.resource(uri, mime_type="text/markdown", description=description)(
            _make_reader(markdown_file)
        )


def _build_server() -> FastMCP:
    """\
    Build and return a configured FastMCP server with all NEF tools and resources registered.

    Tools are discovered automatically from mcp_commands via the @mcp_tool decorator,
    in declaration order. Resources from resources/mcp_server/ are registered as MCP
    resources and also accessible as tools via the nef_list_resources / nef_read_resource
    tools (generated by _NefResourcesAsTools).
    """
    # Use the same function as nef_read_me_first for consistency (without skip header for instructions)
    instructions = _build_full_orientation()

    mcp_server = FastMCP(
        "nef-pipelines", version=get_version(), instructions=instructions
    )

    # Register regular resources (alphabetical order)
    _register_resources(mcp_server, _RESOURCES)

    # Register skill resources (priority order)
    _register_resources(
        mcp_server, _SKILLS, uri_prefix="nef://skill/", sort_key=_resource_sort_key
    )

    for tool_fn in _MCP_TOOLS:
        mcp_server.tool()(tool_fn)

    mcp_server.add_transform(_NefResourcesAsTools(mcp_server))

    return mcp_server
